language: ruby
cache:
  bundler: true
  directories:
    - travis_phantomjs

rvm:
  - 2.3.4
before_install:
  - |
    export PHANTOMJS_VERSION=2.1.1
    export PATH=$PWD/travis_phantomjs/phantomjs-$PHANTOMJS_VERSION-linux-x86_64/bin:$PATH
    if [ $(phantomjs --version) != $PHANTOMJS_VERSION ]; then
      rm -rf $PWD/travis_phantomjs
      mkdir -p $PWD/travis_phantomjs
      wget https://github.com/Medium/phantomjs/releases/download/v$PHANTOMJS_VERSION/phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2
      tar -xvf phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2 -C $PWD/travis_phantomjs
    fi
before_script:
  - bundle exec rake db:create db:migrate
  - bundle exec bundle-audit update
sudo: false
